package io.github.kafkademo.domain;

import java.util.UUID;

/**
 * The wire format: the value on Kafka is this object serialized to JSON
 * (a String on the wire — see docs/06). The id is the dedup key (docs/07 §4).
 *
 * @param id      unique message id — the dedup key, generated by the producer
 * @param content the user's message text
 * @param sentAt  producer-side timestamp (ms since epoch)
 */
public record MessagePayload(String id, String content, long sentAt) {

    public MessagePayload(String content) {
        this(UUID.randomUUID().toString(), content, System.currentTimeMillis());
    }
}
